# My First ML project

My First Machine Learning Project
Dataset: Zomato Restaurants Dataset
Algorithm Used: Linear Regression
Performance Metric: Mean Squared Error

## Load data

In [ ]:
import pandas as pd
df=pd.read_csv("zomato.csv",encoding="latin1",engine="python",on_bad_lines='skip')
df.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [ ]:
df.shape

(7594, 17)

In [ ]:
df.columns

Index(['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)'],
      dtype='object')

In [ ]:
df.info

<bound method DataFrame.info of                                                     url  \
0     https://www.zomato.com/bangalore/jalsa-banasha...
1     https://www.zomato.com/bangalore/spice-elephan...
2     https://www.zomato.com/SanchurroBangalore?cont...
3     https://www.zomato.com/bangalore/addhuri-udupi...
4     https://www.zomato.com/bangalore/grand-village...
...                                                 ...
7589  https://www.zomato.com/bangalore/pita-pocket-f...
7590  https://www.zomato.com/bangalore/the-london-sh...
7591  https://www.zomato.com/bangalore/food-square-m...
7592  https://www.zomato.com/bangalore/aashirvaad-re...
7593  https://www.zomato.com/bangalore/beyond-elemen...

                                                address  \
0     942, 21st Main Road, 2nd Stage, Banashankari, ...
1     2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...
2     1112, Next to KIMS Medical College, 17th Cross...
3     1st Floor, Annakuteera, 3rd Stage, Banashankar...
4     10, 3rd Floor, Lakshmi Associates, Gandhi Baza...
...                                                 ...
7589  12, 60 Feet Road, Vaikuntam Layout, Lakshminar...
7590  6th Cross, Sai Baba Temple Road, Kundalahalli,...
7591  19, Krishna Senate, Outer Ring Road, Near Cana...
7592  117/4, 5th Cross, Shantiniketan Layout, SGR De...
7593  Plot No 7, 4th Floor, Prashanth Layout, Trijal...

                       name online_order book_table   rate  votes  \
0                     Jalsa          Yes        Yes  4.1/5    775
1            Spice Elephant          Yes         No  4.1/5    787
2           San Churro Cafe          Yes         No  3.8/5    918
3     Addhuri Udupi Bhojana           No         No  3.7/5     88
4             Grand Village           No         No  3.8/5    166
...                     ...          ...        ...    ...    ...
7589    Pita Pocket Factory          Yes         No  3.6/5     27
7590      The London Shakes          Yes         No  4.1/5     31
7591            Food Square          Yes         No  3.6/5     16
7592  Aashirvaad Restaurant          Yes         No  3.1/5    249
7593        Beyond Elements          Yes        Yes  4.1/5    859

                                 phone      location            rest_type  \
0       080 42297555\r\n+91 9743772233  Banashankari        Casual Dining
1                         080 41714161  Banashankari        Casual Dining
2                       +91 9663487993  Banashankari  Cafe, Casual Dining
3                       +91 9620009302  Banashankari          Quick Bites
4     +91 8026612447\r\n+91 9901210005  Basavanagudi        Casual Dining
...                                ...           ...                  ...
7589  +91 8043779943\r\n+91 9611214199   Brookefield        Casual Dining
7590      080 67466725\r\n080 42034380  Marathahalli          Quick Bites
7591                    +91 9916999553  Marathahalli          Quick Bites
7592  +91 8105872118\r\n+91 9036799105  Marathahalli          Quick Bites
7593                      080 48500777    Whitefield  Casual Dining, Cafe

                                             dish_liked  \
0     Pasta, Lunch Buffet, Masala Papad, Paneer Laja...
1     Momos, Lunch Buffet, Chocolate Nirvana, Thai G...
2     Churros, Cannelloni, Minestrone Soup, Hot Choc...
3                                           Masala Dosa
4                                   Panipuri, Gol Gappe
...                                                 ...
7589                                                NaN
7590  Pasta, Burgers, Fries, Nachos, Exotic Garlic B...
7591                                                NaN
7592                                                NaN
7593  Masala Chaach, Dal Makhani, Pasta, Wood Fire P...

                                         cuisines approx_cost(for two people)  \
0                  North Indian, Mughlai, Chinese                         800
1                     Chinese, North Indian, Thai                         800
2                          Cafe, Mexican, Italian                         800
3                      South Indian, North Indian                         300
4                        North Indian, Rajasthani                         600
...                                           ...                         ...
7589  Mediterranean, Continental, Italian, Burger                         500
7590                         Fast Food, Beverages                         300
7591                           Fast Food, Chinese                         200
7592                 North Indian, Oriya, Chinese                         300
7593           Cafe, Italian, Pizza, North Indian                         900

                                           reviews_list  \
0     [('Rated 4.0', 'RATED\n  A beautiful place to ...
1     [('Rated 4.0', 'RATED\n  Had been here for din...
2     [('Rated 3.0', "RATED\n  Ambience is not that ...
3     [('Rated 4.0', "RATED\n  Great food and proper...
4     [('Rated 4.0', 'RATED\n  Very good restaurant ...
...                                                 ...
7589  [('Rated 4.0', 'RATED\n  I had ordered Veg sha...
7590  [('Rated 4.0', 'RATED\n  Although it is new on...
7591  [('Rated 1.0', 'RATED\n  The worst food I have...
7592  [('Rated 5.0', 'RATED\n  Just now I order from...
7593  [('Rated 2.0', 'RATED\n  Nothing apart from th...

                                              menu_item listed_in(type)  \
0                                                    []          Buffet
1                                                    []          Buffet
2                                                    []          Buffet
3                                                    []          Buffet
4                                                    []          Buffet
...                                                 ...             ...
7589  ['Hummus [1 Plate]', 'Falafel', 'Shakshuka', '...        Delivery
7590  ['Tandoori Spicy Maggi', 'Classic Fries', 'Cas...        Delivery
7591  ['Paneer Fried Rice', 'Chicken Fried Rice', 'S...        Delivery
7592  ['Veg Thali', 'Dahi Pakhala Thali', 'Chicken T...        Delivery
7593  ['Dal Makhni with 2 Butter Tandoori Rotis', 'D...        Delivery

     listed_in(city)
0       Banashankari
1       Banashankari
2       Banashankari
3       Banashankari
4       Banashankari
...              ...
7589     Brookefield
7590     Brookefield
7591     Brookefield
7592     Brookefield
7593     Brookefield

[7594 rows x 17 columns]>

In [ ]:
df.isnull().sum()

url                               0
address                           0
name                              0
online_order                      0
book_table                        0
rate                           1066
votes                             0
phone                           147
location                          1
rest_type                        32
dish_liked                     4246
cuisines                          9
approx_cost(for two people)      14
reviews_list                      0
menu_item                         0
listed_in(type)                   0
listed_in(city)                   0
dtype: int64

In [ ]:
df = df.drop(['url','address','phone','menu_item','reviews_list','dish_liked'], axis=1)
df.head()

,name,online_order,book_table,rate,votes,location,rest_type,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1/5,775,Banashankari,Casual Dining,"North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1/5,787,Banashankari,Casual Dining,"Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8/5,918,Banashankari,"Cafe, Casual Dining","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,Banashankari,Quick Bites,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8/5,166,Basavanagudi,Casual Dining,"North Indian, Rajasthani",600,Buffet,Banashankari

In [ ]:
df.isnull().sum()

name                              0
online_order                      0
book_table                        0
rate                           1066
votes                             0
location                          1
rest_type                        32
cuisines                          9
approx_cost(for two people)      14
listed_in(type)                   0
listed_in(city)                   0
dtype: int64

In [ ]:
df=df.dropna()

In [ ]:
df.shape

(6498, 11)

In [ ]:
df = df[df['rate'] != 'NEW']
df = df[df['rate'] != '-']

In [ ]:
df['rate'] = df['rate'].str.replace('/5','')

In [ ]:
df['rate'] = df['rate'].astype(float)

In [ ]:
df['rate'].head()

0    4.1
1    4.1
2    3.8
3    3.7
4    3.8
Name: rate, dtype: float64

In [ ]:
df['online_order'] = df['online_order'].map({'Yes':1, 'No':0})
df['book_table'] = df['book_table'].map({'Yes':1, 'No':0})

In [ ]:
df[['online_order','book_table']].head()

   online_order  book_table
0             1           1
1             1           0
2             1           0
3             0           0
4             0           0

In [ ]:
df = df.drop(['name','location','rest_type','cuisines','listed_in(type)','listed_in(city)'], axis=1)

In [ ]:
df.columns

Index(['online_order', 'book_table', 'rate', 'votes',
       'approx_cost(for two people)'],
      dtype='object')

In [ ]:
df = df.rename(columns={'approx_cost(for two people)': 'cost'})
df['cost'] = df['cost'].str.replace(',', '').astype(float)

X = df[['online_order','book_table','votes','cost']]
y = df['rate']

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [ ]:
from sklearn.metrics import mean_squared_error

y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)

print("Mean Squared Error:", mse)

Mean Squared Error: 0.12942423802446998

In [ ]:
print("Model training completed successfully")
print("Mean Squared Error:", mse)

Model training completed successfully
Mean Squared Error: 0.12942423802446998